### ISSUE TITLE
Create Admin UI

### ISSUE THREAD

**Issue by simplytunde** [WuraLab/Boardly#17]

**Comment by simplytunde** [comment]
@phawazzzy This issue tracks the create admin UI PR. Once you create the PR, link it to this issue.

**Comment by phawazzzy** [comment]
<img width="909" alt="Screenshot 2021-02-24 at 18 07 17" src="https://user-images.githubusercontent.com/36922198/109037587-28360680-76cb-11eb-981e-2e67b111fb9b.png">


Running the web app and i get this error above

**Comment by simplytunde** [comment]
I will submit a standard PR to document  how we will run our  frontend and backend. You can find a temp way to run the application for now.
