### ISSUE TITLE
Unable to find some modules

### ISSUE THREAD

**Issue by phawazzzy** [WuraLab/Boardly#50]
This error was gotten when I pulled the master branch.

These files exist but the still getting this error

**How I got**
pulled master from upstream

**What I have done**
I thought I have messed up with git history, so I deleted the project folder on my machine then cloned the project again.
I still have the same error.
<img width="1280" alt="Screenshot 2021-03-18 at 06 46 13" src="https://user-images.githubusercontent.com/36922198/111579088-a448d900-87b5-11eb-93f6-fe4a5e648359.png">

**Comment by phawazzzy** [comment]
The issue has been solved,
Happens that the package next-images wasn't installing well when i did `npm install`.
I had to manually install it using `npm install next-images`

so i am closing this issue

**Comment by adefemi171** [comment]
@phawazzzy should this be closed?

**Comment by phawazzzy** [comment]
Yes it should
