### ISSUE TITLE
Update UI auth paths

### ISSUE THREAD

**Issue by simplytunde** [WuraLab/Boardly#64]
Currently, we have these paths in the UI views. We should probably update the paths to something more user friendly.
```bash
✗ ls auth
create-admin-view.tsx forgot-password.tsx   login-view.tsx        reset-password.tsx    sign-up-view.tsx
```
I think we can opt for something more  simple and user friendly/

**Comment by nextwebb** [comment]
@simplytunde an example here will be helpful
